"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { CheckCircle, Download } from "lucide-react";
import jsPDF from "jspdf";

export default function LLMPage() {
  const [prompt, setPrompt] = useState("");
  const [lastPrompt, setLastPrompt] = useState("");
  const [response, setResponse] = useState("");
  const [loading, setLoading] = useState(false);
  const [finished, setFinished] = useState(false);

  const [farmerName, setFarmerName] = useState("");
  const [farmerLocation, setFarmerLocation] = useState("");

  // ===============================
  // 🤖 ASK AI
  // ===============================
  const askLLM = async () => {
    if (!prompt.trim()) {
      setResponse("⚠️ Please enter a farming question.");
      return;
    }

    const currentPrompt = prompt;

    setLastPrompt(currentPrompt);
    setPrompt("");
    setResponse("");
    setLoading(true);
    setFinished(false);

    try {
      const res = await fetch("http://localhost:4000/api/llm/ask", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: currentPrompt }),
      });

      const data = await res.json();

      // ✅ Handle backend errors
      if (!res.ok) {
        setResponse("⚠️ " + (data.error || "Server error occurred."));
        setLoading(false);
        return;
      }

      if (!data.answer) {
        setResponse("⚠️ No answer received from AI.");
        setLoading(false);
        return;
      }

      const answer = data.answer;

      let i = 0;
      let typed = "";

      const typeWriter = () => {
        if (i < answer.length) {
          typed += answer[i++];
          setResponse(typed);
          setTimeout(typeWriter, 20);
        } else {
          setLoading(false);
          setFinished(true);
        }
      };

      typeWriter();

    } catch (err) {
      setResponse("⚠️ Backend not running or network error.");
      setLoading(false);
    }
  };

  // ===============================
  // 📄 PDF GENERATION
  // ===============================
  const downloadPDF = () => {
    const pdf = new jsPDF("p", "mm", "a4");
    const w = pdf.internal.pageSize.getWidth();
    const h = pdf.internal.pageSize.getHeight();

    pdf.setFillColor(20, 83, 45);
    pdf.rect(0, 0, w, 38, "F");

    pdf.setTextColor(255);
    pdf.setFont("Times", "Bold");
    pdf.setFontSize(24);
    pdf.text("AGRITRUST AI REPORT", w / 2, 22, { align: "center" });

    pdf.setFontSize(11);
    pdf.setFont("Times", "Normal");
    pdf.text("Smart Farming Assistance", w / 2, 30, { align: "center" });

    pdf.setFillColor(236, 253, 245);
    pdf.roundedRect(10, 45, w / 2 - 15, 30, 6, 6, "F");

    pdf.setTextColor(0);
    pdf.setFont("Times", "Bold");
    pdf.setFontSize(13);
    pdf.text("Farmer Name", 16, 58);

    pdf.setFont("Times", "Normal");
    pdf.text(farmerName || "-", 16, 68);

    pdf.roundedRect(w / 2 + 5, 45, w / 2 - 15, 30, 6, 6, "F");

    pdf.setFont("Times", "Bold");
    pdf.text("Location", w / 2 + 11, 58);

    pdf.setFont("Times", "Normal");
    pdf.text(farmerLocation || "-", w / 2 + 11, 68);

    let y = 85;

    pdf.setFont("Times", "Bold");
    pdf.setFontSize(14);
    pdf.text("Topic / Question", 10, y);

    y += 6;
    pdf.setDrawColor(34, 197, 94);
    pdf.line(10, y, w - 10, y);

    y += 6;
    pdf.setFont("Times", "Normal");
    pdf.setFontSize(11);
    const topicLines = pdf.splitTextToSize(lastPrompt, w - 20);
    pdf.text(topicLines, 10, y);
    y += topicLines.length * 6 + 6;

    pdf.setFont("Times", "Bold");
    pdf.setFontSize(14);
    pdf.text("AI Recommendation", 10, y);

    y += 6;
    pdf.line(10, y, w - 10, y);
    y += 6;

    pdf.setFont("Times", "Normal");
    pdf.setFontSize(11);
    const responseLines = pdf.splitTextToSize(response, w - 20);

    responseLines.forEach((line: string) => {
      if (y > h - 25) {
        pdf.addPage();
        y = 20;
      }

      pdf.setFillColor(240, 253, 244);
      pdf.rect(8, y - 5, w - 16, 8, "F");
      pdf.text(line, 10, y);
      y += 8;
    });

    const pages = pdf.getNumberOfPages();
    for (let i = 1; i <= pages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(9);
      pdf.setTextColor(120);
      pdf.text(
        `Page ${i} of ${pages} • Generated by AgriTrust AI • ${new Date().toLocaleDateString()}`,
        w / 2,
        h - 10,
        { align: "center" }
      );
    }

    pdf.save("AgriTrust_AI_Report.pdf");
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-green-100 to-white flex items-center justify-center p-6">
      <div className="w-full max-w-2xl bg-white rounded-3xl shadow-xl p-6">
        <h1 className="text-3xl font-bold text-green-700 text-center mb-6">
          🌱 Ask AgriTrust AI
        </h1>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
          <input
            type="text"
            placeholder="Farmer Name"
            value={farmerName}
            onChange={(e) => setFarmerName(e.target.value)}
            className="border rounded-xl p-3 focus:ring-2 focus:ring-green-400"
          />
          <input
            type="text"
            placeholder="Location (Village / District)"
            value={farmerLocation}
            onChange={(e) => setFarmerLocation(e.target.value)}
            className="border rounded-xl p-3 focus:ring-2 focus:ring-green-400"
          />
        </div>

        <textarea
          className="w-full border rounded-xl p-4 mb-4"
          rows={3}
          placeholder="Ask your farming question..."
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
        />

        <button
          onClick={askLLM}
          disabled={loading}
          className={`w-full py-3 rounded-xl font-semibold ${
            loading
              ? "bg-gray-400 cursor-not-allowed"
              : "bg-green-600 hover:bg-green-700 text-white"
          }`}
        >
          {loading ? "Thinking..." : "Ask AI"}
        </button>

        <AnimatePresence>
          {response && (
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="mt-6 bg-green-50 p-4 rounded-xl"
            >
              <p className="font-semibold text-green-800 mb-2">
                AI Response
              </p>
              <p className="whitespace-pre-line">{response}</p>

              {finished && (
                <div className="flex justify-between items-center mt-4">
                  <button
                    onClick={downloadPDF}
                    className="flex items-center gap-2 bg-green-600 text-white px-4 py-2 rounded-xl"
                  >
                    <Download size={18} />
                    Download PDF
                  </button>
                  <CheckCircle size={26} className="text-green-600" />
                </div>
              )}
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
